#!/usr/bin/env bash
# =============================================================================
# install-coldfusion.sh
# Installs Adobe ColdFusion 2025 from the ZIP installer variant.
#
# The ZIP installer (ColdFusion_2025_WWEJ_linux64.zip) contains a nested zip:
#   ColdFusion_2025_WWEJ_linux64.zip
#     └── ColdFusion_WWEJ_linux64.zip   (the actual payload — 2269 files)
#           └── ColdFusion/             (full installation tree with bundled JRE 21)
#
# Install is pure file extraction — no installer wizard, no silent.properties.
# Post-extract we:
#   1. Set permissions and fix line endings on shell scripts
#   2. Overwrite password.properties with our training credentials
#   3. Overwrite adminconfig.xml to skip the setup wizard
#   4. Overwrite neo-datasource.xml with pre-configured H2 datasource
#   5. Patch jvm.config heap to lean training values
#   6. Register the CF2025 systemd service via cf-install-init.sh
# =============================================================================
set -euo pipefail

CF_HOME="${CF_HOME:-/opt/coldfusion2025}"
CF_INSTANCE="cfusion"
CF_BIN="${CF_HOME}/${CF_INSTANCE}/bin"
CF_LIB="${CF_HOME}/${CF_INSTANCE}/lib"

# ─── Locate the outer ZIP ────────────────────────────────────────────────────
CANDIDATE_PATHS=(
  "/tmp/cf-downloads/ColdFusion_2025_WWEJ_linux64.zip"
  "/var/cache/cf-installer/ColdFusion_2025_WWEJ_linux64.zip"
  "/tmp/ColdFusion_2025_WWEJ_linux64.zip"
)

OUTER_ZIP=""
for p in "${CANDIDATE_PATHS[@]}"; do
  if [ -f "$p" ]; then
    OUTER_ZIP="$p"
    break
  fi
done

# ─── Extract ─────────────────────────────────────────────────────────────────
if [ -n "$OUTER_ZIP" ]; then
  echo "[CF] Installing ColdFusion 2025 from ZIP: $OUTER_ZIP"

  WORK_DIR=$(mktemp -d)
  trap 'rm -rf "$WORK_DIR"' EXIT

  echo "[CF] Extracting outer ZIP..."
  unzip -q "$OUTER_ZIP" -d "$WORK_DIR"

  # The outer ZIP contains a signed wrapper; the actual payload is inside
  INNER_ZIP=$(find "$WORK_DIR" -name "ColdFusion_WWEJ_linux64.zip" | head -1)
  if [ -z "$INNER_ZIP" ]; then
    echo "[CF] ERROR: Could not find inner ColdFusion_WWEJ_linux64.zip inside $OUTER_ZIP"
    exit 1
  fi

  echo "[CF] Extracting inner ZIP to ${CF_HOME}..."
  mkdir -p "${CF_HOME}"
  # Inner ZIP extracts to ColdFusion/ — strip that prefix into CF_HOME
  unzip -q "$INNER_ZIP" -d "${CF_HOME}"
  # Move ColdFusion/* → CF_HOME/
  mv "${CF_HOME}/ColdFusion/"* "${CF_HOME}/"
  rmdir "${CF_HOME}/ColdFusion"

  echo "[CF] Extraction complete."

else
  echo "[CF] WARNING: No ColdFusion ZIP installer found."
  echo "[CF] Creating stub skeleton. Re-build with the real ZIP for production."
  echo "[CF] Expected at: /var/cache/cf-installer/ColdFusion_2025_WWEJ_linux64.zip"

  mkdir -p \
    "${CF_BIN}" \
    "${CF_LIB}" \
    "${CF_HOME}/${CF_INSTANCE}/logs" \
    "${CF_HOME}/${CF_INSTANCE}/wwwroot" \
    "${CF_HOME}/jre/bin"

  # Minimal stub scripts so systemd units don't hard-fail
  cat > "${CF_BIN}/coldfusion" <<'STUB'
#!/bin/bash
echo "[CF-STUB] ColdFusion stub — real ZIP installer not present at build time."
echo "[CF-STUB] Rebuild with ColdFusion_2025_WWEJ_linux64.zip in downloads/"
case "${1:-}" in
  start) exec sleep infinity ;;
  stop)  exit 0 ;;
  *) echo "Usage: coldfusion {start|stop|status}"; exit 1 ;;
esac
STUB
  chmod +x "${CF_BIN}/coldfusion"

  cat > "${CF_BIN}/cfstart.sh" <<'STUB'
#!/bin/bash
CF_DIR=$(cd "$(dirname "$0")"; pwd)/..
$CF_DIR/bin/coldfusion start
STUB
  cat > "${CF_BIN}/cfstop.sh" <<'STUB'
#!/bin/bash
CF_DIR=$(cd "$(dirname "$0")"; pwd)/..
$CF_DIR/bin/coldfusion stop
STUB
  chmod +x "${CF_BIN}/cfstart.sh" "${CF_BIN}/cfstop.sh"

  ln -sf "$(command -v java 2>/dev/null || echo /usr/bin/java)" \
         "${CF_HOME}/jre/bin/java" 2>/dev/null || true
fi

# ─── Fix permissions on all shell scripts ────────────────────────────────────
echo "[CF] Setting permissions..."
find "${CF_HOME}" -name "*.sh" -exec chmod +x {} \;
chmod +x "${CF_BIN}/coldfusion" 2>/dev/null || true
find "${CF_LIB}" -name "*.xml" -exec chmod 644 {} \; 2>/dev/null || true
chmod -R 755 "${CF_BIN}" 2>/dev/null || true

# Fix Windows CRLF line endings in shell scripts (common in ZIP installers)
if command -v dos2unix >/dev/null 2>&1; then
  find "${CF_HOME}" -name "*.sh" -exec dos2unix -q {} \; 2>/dev/null || true
  dos2unix -q "${CF_BIN}/coldfusion" 2>/dev/null || true
else
  find "${CF_HOME}" -name "*.sh" -exec sed -i 's/\r//' {} \; 2>/dev/null || true
  sed -i 's/\r//' "${CF_BIN}/coldfusion" 2>/dev/null || true
fi

# ─── Admin password ───────────────────────────────────────────────────────────
# The real password hash for "training" must be generated by CF itself on first
# boot (it uses a salted SHA-256). We set it to empty here so that CF 2025
# prompts for a password on the very first admin login — OR we set a known hash.
#
# Hash below is the one shipped in the ZIP (the CF trial default).
# Replace with your own by running:
#   cd /opt/coldfusion2025/cfusion/bin
#   java -jar cf-passwordreset.jar set <newpassword>
# and copying the resulting password.properties value.
echo "[CF] Writing password.properties..."
cat > "${CF_LIB}/password.properties" <<'EOF'
#ColdFusion 2025 Training Environment
#Password: training  (change before production use)
password=42A44B0C2D612224587A943D0DDD8AC8FBB39C61807C1C46356008D5D684373E
rdspassword=74S/JbKKrp5n5MTlaXJu4Gw1zbzjDaG/crE2nvmCW7A\=
encrypted=true
EOF

# ─── Skip setup wizard ───────────────────────────────────────────────────────
echo "[CF] Configuring adminconfig.xml (skip setup wizard)..."
cat > "${CF_LIB}/adminconfig.xml" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<setupconfig>
    <runsetupwizard>false</runsetupwizard>
    <runsecureprofile>false</runsecureprofile>
    <runmigrationwizard>false</runmigrationwizard>
    <runmxmigrationwizard>false</runmxmigrationwizard>
    <migratecf2021>false</migratecf2021>
    <migratecf2023>false</migratecf2023>
    <migratecf2025>false</migratecf2025>
    <setupoptions>
        <sampleapps>false</sampleapps>
        <odbc>false</odbc>
        <enablerds>false</enablerds>
    </setupoptions>
</setupconfig>
EOF

# ─── Pre-configured datasources ──────────────────────────────────────────────
echo "[CF] Writing neo-datasource.xml..."
cp /tmp/neo-datasource.xml "${CF_LIB}/neo-datasource.xml"

# ─── Patch JVM heap in jvm.config ─────────────────────────────────────────────
# The ZIP ships with -Xms256m -Xmx1024m — keep Xms, lower Xmx for microVM
if [ -f "${CF_BIN}/jvm.config" ]; then
  echo "[CF] Patching jvm.config heap..."
  sed -i 's/-Xmx[0-9]*[mMgG]/-Xmx512m/' "${CF_BIN}/jvm.config"
fi

# ─── Accept EULA ─────────────────────────────────────────────────────────────
# CF 2025 ZIP installer ships with EULA_ACCEPTED= (empty) in licenseinfo.properties.
# The coldfusion start script checks this and refuses to boot if not set to true.
echo "[CF] Pre-accepting ColdFusion EULA (licenseinfo.properties)..."
if [ -f "${CF_LIB}/licenseinfo.properties" ]; then
  sed -i 's/EULA_ACCEPTED=/EULA_ACCEPTED=true/' "${CF_LIB}/licenseinfo.properties"
else
  echo "EULA_ACCEPTED=true" > "${CF_LIB}/licenseinfo.properties"
fi

# ─── H2 embedded JDBC driver ─────────────────────────────────────────────────
# CF 2025 ships with zero JDBC drivers. We download H2 (self-contained, no
# server needed) for the training_db datasource used in DB exercises.
H2_VERSION="2.2.224"
H2_JAR="${CF_HOME}/${CF_INSTANCE}/lib/h2-${H2_VERSION}.jar"
H2_LOCAL="/tmp/cf-downloads/h2-${H2_VERSION}.jar"
H2_MAVEN="https://repo1.maven.org/maven2/com/h2database/h2/${H2_VERSION}/h2-${H2_VERSION}.jar"

echo "[CF] Installing H2 JDBC driver..."
if [ -f "${H2_LOCAL}" ]; then
  cp "${H2_LOCAL}" "${H2_JAR}"
elif curl -fsSL --retry 3 -o "${H2_JAR}" "${H2_MAVEN}"; then
  echo "[CF] H2 downloaded from Maven."
else
  echo "[CF] WARNING: Could not obtain H2 jar — training_db datasource will not work."
fi

# ─── Create log and db directories ───────────────────────────────────────────
mkdir -p \
  "${CF_HOME}/${CF_INSTANCE}/logs" \
  "${CF_HOME}/${CF_INSTANCE}/db"

# ─── Install optional CF packages ────────────────────────────────────────────
# Packages for intermediate/advanced training curriculum.
# Each installs independently — one failure won't abort the rest.
if [ -f "${CF_BIN}/cfpm.sh" ]; then
  echo "[CF] Installing optional CF packages via cfpm.sh..."
  chmod +x "${CF_BIN}/cfpm.sh"
  for pkg in document orm mail debugger websocket zip \
             ai milvus chroma; do
    echo "[CF] Installing package: ${pkg}..."
    bash "${CF_BIN}/cfpm.sh" install "${pkg}" 2>/dev/null || \
      echo "[CF] WARNING: package ${pkg} failed (non-fatal)"
  done
  echo "[CF] Package installation complete."
else
  echo "[CF] WARNING: cfpm.sh not found — skipping optional packages."
fi

# ─── Register systemd service via CF's own init script ───────────────────────
if [ -f "${CF_BIN}/cf-install-init.sh" ]; then
  echo "[CF] Registering CF2025 systemd service..."
  bash "${CF_BIN}/cf-install-init.sh" install 2>/dev/null || true
fi

echo "[CF] ColdFusion 2025 installation complete. CF_HOME=${CF_HOME}"
